### ISSUE TITLE
Improving security and code managability

### ISSUE THREAD

**Issue by Royalatomo** [Micro-Security/React-Message-Application#1]
I saw in your code that the APIs and other important information is placed directly inside the file. And the code isn't mangable all the functions are put in the single file which makes it harder for programmers to read and understand. 
What I would like to do?

1) Store API Key and other important information in environment variables
2) There is an issue in message showing so I will try to solve the bug
3) Break the functions into components

**Comment by Micro-Security** [comment]
Sure go ahead

**Comment by Royalatomo** [comment]
I have actually already completed the changes could I directly make a pull request

**Comment by Micro-Security** [comment]
yeah sure
